name: RLWalk
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - setuptools
  - wheel
  - ca-certificates
  - openssl
  - sqlite
  - zlib
  - xz
  - tk
  - ncurses
  - pip:
    - absl-py
    - atari-py
    - attrs
    - black
    - cachetools
    - click
    - cloudpickle
    - cmaes
    - colorama
    - coverage
    - cycler
    - decorator
    - execnet
    - flake8
    - gym-minigrid
    - jinja2
    - joblib
    - kiwisolver
    - matplotlib
    - networkx
    - ninja
    - numpy
    - opencv-python
    - optuna  # Latest version (use TPESampler instead of SkoptSampler)
    - packaging
    - panda-gym
    - pandas
    - pathspec
    - pillow
    - plotly
    - protobuf
    - psutil
    - pybullet
    - pygments
    - pyparsing
    - pytest
    - python-dateutil
    - pytz
    - pyyaml
    - requests
    - rsa
    - sb3-contrib  # Latest version of Stable-Baselines3 contrib
    - scikit-learn
    - scipy
    - seaborn
    - sqlalchemy
    - tensorboard
    - threadpoolctl
    - tomli
    - tqdm
    - typing-extensions
    - urllib3
    - werkzeug
