wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    code_path: code/Catcher_Flappy_Continuous/cleanrl/cleanrl/ppo.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.15
    start_time: 1729597592.654673
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 3
      - 13
      - 16
      - 23
      - 35
      4: 3.10.15
      5: 0.13.11
      8:
      - 4
      - 5
anneal_lr:
  desc: null
  value: true
batch_size:
  desc: null
  value: 1280
capture_video:
  desc: null
  value: false
clip_coef:
  desc: null
  value: 0.2
clip_vloss:
  desc: null
  value: true
cuda:
  desc: null
  value: true
ent_coef:
  desc: null
  value: 0.01
env_id:
  desc: null
  value: FlappyBird
exp_name:
  desc: null
  value: ppo
gae_lambda:
  desc: null
  value: 0.95
gamma:
  desc: null
  value: 0.9
learning_rate:
  desc: null
  value: 0.0005
max_grad_norm:
  desc: null
  value: 0.5
minibatch_size:
  desc: null
  value: 320
norm_adv:
  desc: null
  value: true
num_envs:
  desc: null
  value: 10
num_iterations:
  desc: null
  value: 3906
num_minibatches:
  desc: null
  value: 4
num_steps:
  desc: null
  value: 128
seed:
  desc: null
  value: 1
target_kl:
  desc: null
  value: null
torch_deterministic:
  desc: null
  value: true
total_timesteps:
  desc: null
  value: 5000000
track:
  desc: null
  value: true
update_epochs:
  desc: null
  value: 4
vf_coef:
  desc: null
  value: 0.5
wandb_entity:
  desc: null
  value: null
wandb_project_name:
  desc: null
  value: AIProbe-Catcher
